properties
# Telegram Bot
server.port=8080
telegram.bot.token=8545778654:AAHZjyn5bcatjnO3LbE89oP1fCOD9g8PAhE
telegram.bot.username=germes_travel_bot

# Redis (упрощённая конфигурация без URL)
spring.data.redis.host=easy-dory-77710.upstash.io
spring.data.redis.port=6379

# Server
server.port=8080

# Logging
logging.level.org.springframework=INFO
logging.level.com.toursearch=DEBUG

