spring.application.name=tour-search-api
server.port=8080
spring.data.redis.url=redis://default:gQAAAAAAAS-OAAIncDE2ZjQzMmM0ODY2YWM0NjAzOGYyZjdmZmFkYTM0NTkwZHAxNzc3MTA@easy-dory-77710.upstash.io:6379
telegram.bot.username=germes_travel_bot
