spring.application.name=tour-search-api
properties
server.port=8080
spring.data.redis.url=redis://default:gQAAAAAAAS-OAAIncDE2ZjQzMmM0ODY2YWM0NjAzOGYyZjdmZmFkYTM0NTkwZHAxNzc3MTA@easy-dory-77710.upstash.io:6379
telegram.bot.token=AAHzjyn5bcatJnO3LbE89OP1fCD09g8PhnE