properties
# Server
server.port=8080

# Telegram Bot
telegram.bot.token=8545778654:AAHZjyn5bcatjnO3LbE89oP1fCOD9g8PAhE
telegram.bot.username=germes_travel_bot
telegram.bot.webapp-url=https://frontend-woad-five-65.vercel.app

# Отключаем Redis
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

# Logging
logging.level.org.springframework=INFO
logging.level.com.toursearch=DEBUG

